// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  requestId: __t.u64().name("request_id"),
  sequence: __t.u32(),
  label: __t.string(),
  detail: __t.string(),
  status: __t.string(),
  screenshotRef: __t.string().name("screenshot_ref"),
  createdAt: __t.timestamp().name("created_at"),
});
