// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.string().name("room_id"),
  sourceSegmentId: __t.u64().name("source_segment_id"),
  prompt: __t.string(),
  targetService: __t.string().name("target_service"),
  windowMinutes: __t.u32().name("window_minutes"),
  constraints: __t.string(),
  status: __t.string(),
  requestedBy: __t.identity().name("requested_by"),
  approvedBy: __t.option(__t.identity()).name("approved_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
