// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentStep = __t.object("AgentStep", {
  id: __t.u64(),
  requestId: __t.u64(),
  sequence: __t.u32(),
  label: __t.string(),
  detail: __t.string(),
  status: __t.string(),
  screenshotRef: __t.string(),
  createdAt: __t.timestamp(),
});
export type AgentStep = __Infer<typeof AgentStep>;

export const Approval = __t.object("Approval", {
  id: __t.u64(),
  requestId: __t.u64(),
  actor: __t.identity(),
  decision: __t.string(),
  createdAt: __t.timestamp(),
});
export type Approval = __Infer<typeof Approval>;

export const Conclusion = __t.object("Conclusion", {
  requestId: __t.u64(),
  summary: __t.string(),
  confidence: __t.string(),
  recommendation: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type Conclusion = __Infer<typeof Conclusion>;

export const ConnectorCredential = __t.object("ConnectorCredential", {
  id: __t.string(),
  owner: __t.identity(),
  provider: __t.string(),
  secretJson: __t.string(),
  settingsJson: __t.string(),
  status: __t.string(),
  sampleJson: __t.string(),
  createdAt: __t.timestamp(),
  checkedAt: __t.timestamp(),
});
export type ConnectorCredential = __Infer<typeof ConnectorCredential>;

export const ConnectorRequestGate = __t.object("ConnectorRequestGate", {
  id: __t.string(),
  owner: __t.identity(),
  provider: __t.string(),
  lastAttemptAt: __t.timestamp(),
});
export type ConnectorRequestGate = __Infer<typeof ConnectorRequestGate>;

export const Evidence = __t.object("Evidence", {
  id: __t.u64(),
  requestId: __t.u64(),
  kind: __t.string(),
  headline: __t.string(),
  detail: __t.string(),
  value: __t.string(),
  createdAt: __t.timestamp(),
});
export type Evidence = __Infer<typeof Evidence>;

export const IncidentRoom = __t.object("IncidentRoom", {
  roomId: __t.string(),
  title: __t.string(),
  severity: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type IncidentRoom = __Infer<typeof IncidentRoom>;

export const InvestigationRequest = __t.object("InvestigationRequest", {
  id: __t.u64(),
  roomId: __t.string(),
  sourceSegmentId: __t.u64(),
  prompt: __t.string(),
  targetService: __t.string(),
  windowMinutes: __t.u32(),
  constraints: __t.string(),
  status: __t.string(),
  requestedBy: __t.identity(),
  approvedBy: __t.option(__t.identity()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type InvestigationRequest = __Infer<typeof InvestigationRequest>;

export const Participant = __t.object("Participant", {
  id: __t.u64(),
  roomId: __t.string(),
  identity: __t.identity(),
  displayName: __t.string(),
  role: __t.string(),
  online: __t.bool(),
  joinedAt: __t.timestamp(),
});
export type Participant = __Infer<typeof Participant>;

export const TimelineEvent = __t.object("TimelineEvent", {
  id: __t.u64(),
  roomId: __t.string(),
  eventType: __t.string(),
  actor: __t.string(),
  body: __t.string(),
  createdAt: __t.timestamp(),
});
export type TimelineEvent = __Infer<typeof TimelineEvent>;

export const TranscriptRun = __t.object("TranscriptRun", {
  roomId: __t.string(),
  runId: __t.string(),
  presenter: __t.identity(),
  startedAt: __t.timestamp(),
});
export type TranscriptRun = __Infer<typeof TranscriptRun>;

export const TranscriptSegment = __t.object("TranscriptSegment", {
  id: __t.u64(),
  roomId: __t.string(),
  sequence: __t.u32(),
  speaker: __t.string(),
  text: __t.string(),
  relevant: __t.bool(),
  createdAt: __t.timestamp(),
  interimText: __t.string(),
  isFinal: __t.bool(),
});
export type TranscriptSegment = __Infer<typeof TranscriptSegment>;

