// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddEvidenceReducer from "../add_evidence_reducer";
import AppendTranscriptSegmentReducer from "../append_transcript_segment_reducer";
import ApproveInvestigationReducer from "../approve_investigation_reducer";
import CompleteInvestigationReducer from "../complete_investigation_reducer";
import CreateDemoRoomReducer from "../create_demo_room_reducer";
import EditInvestigationWindowReducer from "../edit_investigation_window_reducer";
import JoinRoomReducer from "../join_room_reducer";
import PauseInvestigationReducer from "../pause_investigation_reducer";
import ProposeInvestigationReducer from "../propose_investigation_reducer";
import RecordAgentStepReducer from "../record_agent_step_reducer";
import ResetDemoReducer from "../reset_demo_reducer";
import StartInvestigationReducer from "../start_investigation_reducer";

export type AddEvidenceParams = __Infer<typeof AddEvidenceReducer>;
export type AppendTranscriptSegmentParams = __Infer<typeof AppendTranscriptSegmentReducer>;
export type ApproveInvestigationParams = __Infer<typeof ApproveInvestigationReducer>;
export type CompleteInvestigationParams = __Infer<typeof CompleteInvestigationReducer>;
export type CreateDemoRoomParams = __Infer<typeof CreateDemoRoomReducer>;
export type EditInvestigationWindowParams = __Infer<typeof EditInvestigationWindowReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type PauseInvestigationParams = __Infer<typeof PauseInvestigationReducer>;
export type ProposeInvestigationParams = __Infer<typeof ProposeInvestigationReducer>;
export type RecordAgentStepParams = __Infer<typeof RecordAgentStepReducer>;
export type ResetDemoParams = __Infer<typeof ResetDemoReducer>;
export type StartInvestigationParams = __Infer<typeof StartInvestigationReducer>;

